// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveApiKeysByTenantID = `-- name: CountActiveApiKeysByTenantID :one
SELECT
	COUNT(*)
FROM
	api_keys
WHERE
	tenant_id = $1
	AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) CountActiveApiKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveApiKeysByTenantID, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countApiKeysByTenantID = `-- name: CountApiKeysByTenantID :one
SELECT
	COUNT(*)
FROM
	api_keys
WHERE
	tenant_id = $1
`

func (q *Queries) CountApiKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countApiKeysByTenantID, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO
	api_keys (tenant_id, name, hashed_key, scopes)
VALUES
	($1, $2, $3, $4)
RETURNING
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
`

type CreateApiKeyParams struct {
	TenantID  pgtype.UUID
	Name      string
	HashedKey string
	Scopes    []string
}

func (q *Queries) CreateApiKey(ctx context.Context, arg CreateApiKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey,
		arg.TenantID,
		arg.Name,
		arg.HashedKey,
		arg.Scopes,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.HashedKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteApiKey = `-- name: DeleteApiKey :exec
DELETE FROM
	api_keys
WHERE
	id = $1
`

func (q *Queries) DeleteApiKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiKey, id)
	return err
}

const deleteApiKeysByTenantID = `-- name: DeleteApiKeysByTenantID :exec
DELETE FROM
	api_keys
WHERE
	tenant_id = $1
`

func (q *Queries) DeleteApiKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteApiKeysByTenantID, tenantID)
	return err
}

const getApiKeyByHashedKey = `-- name: GetApiKeyByHashedKey :one
SELECT
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
FROM
	api_keys
WHERE
	hashed_key = $1
`

func (q *Queries) GetApiKeyByHashedKey(ctx context.Context, hashedKey string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByHashedKey, hashedKey)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.HashedKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getApiKeyByID = `-- name: GetApiKeyByID :one
SELECT
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
FROM
	api_keys
WHERE
	id = $1
`

func (q *Queries) GetApiKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.HashedKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listActiveApiKeysByTenantID = `-- name: ListActiveApiKeysByTenantID :many
SELECT
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
FROM
	api_keys
WHERE
	tenant_id = $1
	AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY
	created_at DESC,
	id DESC
`

func (q *Queries) ListActiveApiKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listActiveApiKeysByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.HashedKey,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApiKeysByTenantID = `-- name: ListApiKeysByTenantID :many
SELECT
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
FROM
	api_keys
WHERE
	tenant_id = $1
ORDER BY
	created_at DESC,
	id DESC
`

func (q *Queries) ListApiKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeysByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.HashedKey,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredApiKeys = `-- name: ListExpiredApiKeys :many
SELECT
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
FROM
	api_keys
WHERE
	expires_at IS NOT NULL
	AND expires_at <= NOW()
ORDER BY
	expires_at DESC
`

func (q *Queries) ListExpiredApiKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listExpiredApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.HashedKey,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleApiKeys = `-- name: ListStaleApiKeys :many
SELECT
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
FROM
	api_keys
WHERE
	(last_used_at IS NULL OR last_used_at < NOW() - INTERVAL '30 days')
	AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY
	last_used_at ASC NULLS FIRST
`

func (q *Queries) ListStaleApiKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listStaleApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.HashedKey,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setApiKeyExpiration = `-- name: SetApiKeyExpiration :one
UPDATE
	api_keys
SET
	expires_at = $1
WHERE
	id = $2
RETURNING
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
`

type SetApiKeyExpirationParams struct {
	ExpiresAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) SetApiKeyExpiration(ctx context.Context, arg SetApiKeyExpirationParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, setApiKeyExpiration, arg.ExpiresAt, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.HashedKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateApiKeyName = `-- name: UpdateApiKeyName :one
UPDATE
	api_keys
SET
	name = $1
WHERE
	id = $2
RETURNING
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
`

type UpdateApiKeyNameParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateApiKeyName(ctx context.Context, arg UpdateApiKeyNameParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateApiKeyName, arg.Name, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.HashedKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateApiKeyScopes = `-- name: UpdateApiKeyScopes :one
UPDATE
	api_keys
SET
	scopes = $1
WHERE
	id = $2
RETURNING
	id, tenant_id, name, hashed_key, scopes, created_at, updated_at, last_used_at, expires_at
`

type UpdateApiKeyScopesParams struct {
	Scopes []string
	ID     pgtype.UUID
}

func (q *Queries) UpdateApiKeyScopes(ctx context.Context, arg UpdateApiKeyScopesParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateApiKeyScopes, arg.Scopes, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.HashedKey,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateLastUsedAtIfStale = `-- name: UpdateLastUsedAtIfStale :exec
UPDATE
	api_keys
SET
	last_used_at = NOW()
WHERE
	id = $1
	AND (last_used_at IS NULL OR last_used_at < NOW() - INTERVAL '5 minutes')
`

func (q *Queries) UpdateLastUsedAtIfStale(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastUsedAtIfStale, id)
	return err
}
