// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIKeysByTenantID = `-- name: CountAPIKeysByTenantID :one
SELECT
        COUNT(*)
FROM
        api_keys
WHERE
        tenant_id = $1
`

func (q *Queries) CountAPIKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeysByTenantID, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countActiveAPIKeysByTenantID = `-- name: CountActiveAPIKeysByTenantID :one
SELECT
        COUNT(*)
FROM
        api_keys
WHERE
        tenant_id = $1
        AND (expires_at IS NULL OR expires_at > NOW())
`

func (q *Queries) CountActiveAPIKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAPIKeysByTenantID, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO
        api_keys (tenant_id, name, token_id, hashed_secret, scopes)
VALUES
        ($1, $2, $3, $4, $5)
RETURNING
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
`

type CreateAPIKeyParams struct {
	TenantID     pgtype.UUID
	Name         string
	TokenID      string
	HashedSecret string
	Scopes       []string
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.Name,
		arg.TokenID,
		arg.HashedSecret,
		arg.Scopes,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.TokenID,
		&i.HashedSecret,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM
        api_keys
WHERE
        id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const deleteAPIKeysByTenantID = `-- name: DeleteAPIKeysByTenantID :exec
DELETE FROM
        api_keys
WHERE
        tenant_id = $1
`

func (q *Queries) DeleteAPIKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAPIKeysByTenantID, tenantID)
	return err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
FROM
        api_keys
WHERE
        id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id pgtype.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.TokenID,
		&i.HashedSecret,
	)
	return i, err
}

const getAPIKeyByTokenID = `-- name: GetAPIKeyByTokenID :one
SELECT
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
FROM
        api_keys
WHERE
        token_id = $1
`

func (q *Queries) GetAPIKeyByTokenID(ctx context.Context, tokenID string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByTokenID, tokenID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.TokenID,
		&i.HashedSecret,
	)
	return i, err
}

const listAPIKeysByTenantID = `-- name: ListAPIKeysByTenantID :many
SELECT
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
FROM
        api_keys
WHERE
        tenant_id = $1
ORDER BY
        created_at DESC,
        id DESC
`

func (q *Queries) ListAPIKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.TokenID,
			&i.HashedSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveAPIKeysByTenantID = `-- name: ListActiveAPIKeysByTenantID :many
SELECT
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
FROM
        api_keys
WHERE
        tenant_id = $1
        AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY
        created_at DESC,
        id DESC
`

func (q *Queries) ListActiveAPIKeysByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listActiveAPIKeysByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.TokenID,
			&i.HashedSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAPIKeys = `-- name: ListExpiredAPIKeys :many
SELECT
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
FROM
        api_keys
WHERE
        expires_at IS NOT NULL
        AND expires_at <= NOW()
ORDER BY
        expires_at DESC
`

func (q *Queries) ListExpiredAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listExpiredAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.TokenID,
			&i.HashedSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAPIKeys = `-- name: ListStaleAPIKeys :many
SELECT
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
FROM
        api_keys
WHERE
        (last_used_at IS NULL OR last_used_at < NOW() - INTERVAL '30 days')
        AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY
        last_used_at ASC NULLS FIRST
`

func (q *Queries) ListStaleAPIKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listStaleAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Scopes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.TokenID,
			&i.HashedSecret,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAPIKeyExpiration = `-- name: SetAPIKeyExpiration :one
UPDATE
        api_keys
SET
        expires_at = $1
WHERE
        id = $2
RETURNING
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
`

type SetAPIKeyExpirationParams struct {
	ExpiresAt pgtype.Timestamptz
	ID        pgtype.UUID
}

func (q *Queries) SetAPIKeyExpiration(ctx context.Context, arg SetAPIKeyExpirationParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, setAPIKeyExpiration, arg.ExpiresAt, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.TokenID,
		&i.HashedSecret,
	)
	return i, err
}

const updateAPIKeyName = `-- name: UpdateAPIKeyName :one
UPDATE
        api_keys
SET
        name = $1
WHERE
        id = $2
RETURNING
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
`

type UpdateAPIKeyNameParams struct {
	Name string
	ID   pgtype.UUID
}

func (q *Queries) UpdateAPIKeyName(ctx context.Context, arg UpdateAPIKeyNameParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKeyName, arg.Name, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.TokenID,
		&i.HashedSecret,
	)
	return i, err
}

const updateAPIKeyScopes = `-- name: UpdateAPIKeyScopes :one
UPDATE
        api_keys
SET
        scopes = $1
WHERE
        id = $2
RETURNING
        id, tenant_id, name, scopes, created_at, updated_at, last_used_at, expires_at, token_id, hashed_secret
`

type UpdateAPIKeyScopesParams struct {
	Scopes []string
	ID     pgtype.UUID
}

func (q *Queries) UpdateAPIKeyScopes(ctx context.Context, arg UpdateAPIKeyScopesParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, updateAPIKeyScopes, arg.Scopes, arg.ID)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Scopes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.TokenID,
		&i.HashedSecret,
	)
	return i, err
}

const updateLastUsedAtIfStale = `-- name: UpdateLastUsedAtIfStale :exec
UPDATE
        api_keys
SET
        last_used_at = NOW()
WHERE
        id = $1
        AND (last_used_at IS NULL OR last_used_at < NOW() - INTERVAL '5 minutes')
`

func (q *Queries) UpdateLastUsedAtIfStale(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateLastUsedAtIfStale, id)
	return err
}
