// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         pgtype.UUID
	TenantID   pgtype.UUID
	Name       string
	HashedKey  string
	Scopes     []string
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
}

type Tenant struct {
	ID        pgtype.UUID
	Name      string
	Email     string
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
