// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"time"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthErrorResponseCode.
const (
	EXPIREDAPIKEY AuthErrorResponseCode = "EXPIRED_API_KEY"
	INVALIDAPIKEY AuthErrorResponseCode = "INVALID_API_KEY"
	MISSINGAPIKEY AuthErrorResponseCode = "MISSING_API_KEY"
)

// Valid indicates whether the value is a known member of the AuthErrorResponseCode enum.
func (e AuthErrorResponseCode) Valid() bool {
	switch e {
	case EXPIREDAPIKEY:
		return true
	case INVALIDAPIKEY:
		return true
	case MISSINGAPIKEY:
		return true
	default:
		return false
	}
}

// Defines values for TenantStatus.
const (
	Active   TenantStatus = "active"
	Inactive TenantStatus = "inactive"
)

// Valid indicates whether the value is a known member of the TenantStatus enum.
func (e TenantStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Inactive:
		return true
	default:
		return false
	}
}

// AuthErrorResponse defines model for AuthErrorResponse.
type AuthErrorResponse struct {
	// Code Machine-readable error code
	Code AuthErrorResponseCode `json:"code"`

	// Error Error message
	Error string `json:"error"`
}

// AuthErrorResponseCode Machine-readable error code
type AuthErrorResponseCode string

// CreateAPIKeyRequest defines model for CreateAPIKeyRequest.
type CreateAPIKeyRequest struct {
	// Name Human-readable name for the API key
	Name string `json:"name"`

	// Scopes List of scopes/permissions for this key
	Scopes *[]string `json:"scopes,omitempty"`

	// TenantId Tenant UUID that owns this API key
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// CreateAPIKeyResponse defines model for CreateAPIKeyResponse.
type CreateAPIKeyResponse struct {
	// ApiKey The actual API key (shown once, must be stored by user)
	ApiKey string `json:"api_key"`

	// Id UUID of the API key record
	Id openapi_types.UUID `json:"id"`

	// Name Name of the API key
	Name string `json:"name"`

	// Scopes List of scopes for this key
	Scopes *[]string `json:"scopes,omitempty"`

	// TenantId Tenant UUID that owns this key
	TenantId openapi_types.UUID `json:"tenant_id"`
}

// CreateTenantRequest defines model for CreateTenantRequest.
type CreateTenantRequest struct {
	// Email Contact email for the tenant
	Email openapi_types.Email `json:"email"`

	// Name Name of the new tenant
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	// Error Error message
	Error string `json:"error"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Checks Additional health checks
	Checks *map[string]string `json:"checks,omitempty"`

	// Status Health status
	Status string `json:"status"`

	// Timestamp Timestamp of the check
	Timestamp string `json:"timestamp"`
}

// Tenant defines model for Tenant.
type Tenant struct {
	// CreatedAt Timestamp when tenant was created
	CreatedAt time.Time `json:"created_at"`

	// Email Tenant contact email
	Email openapi_types.Email `json:"email"`

	// Id Unique identifier for the tenant
	Id openapi_types.UUID `json:"id"`

	// Name Tenant name
	Name string `json:"name"`

	// Status Tenant status
	Status TenantStatus `json:"status"`

	// UpdatedAt Timestamp of last update
	UpdatedAt time.Time `json:"updated_at"`
}

// TenantListResponse defines model for TenantListResponse.
type TenantListResponse struct {
	// Items List of tenants
	Items []Tenant `json:"items"`
}

// TenantStatus Tenant status
type TenantStatus string

// UpdateTenantStatusRequest defines model for UpdateTenantStatusRequest.
type UpdateTenantStatusRequest struct {
	// Status Tenant status
	Status TenantStatus `json:"status"`
}

// UploadURLResponse defines model for UploadURLResponse.
type UploadURLResponse struct {
	// UploadURL Pre-signed URL for uploading media
	UploadURL string `json:"uploadURL"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Forbidden defines model for Forbidden.
type Forbidden = AuthErrorResponse

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = AuthErrorResponse

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// GetMediaUploadURLJSONBody defines parameters for GetMediaUploadURL.
type GetMediaUploadURLJSONBody = map[string]interface{}

// ListTenantsParams defines parameters for ListTenants.
type ListTenantsParams struct {
	// Limit Maximum number of results
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of results to skip
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateApiKeyJSONRequestBody defines body for CreateApiKey for application/json ContentType.
type CreateApiKeyJSONRequestBody = CreateAPIKeyRequest

// GetMediaUploadURLJSONRequestBody defines body for GetMediaUploadURL for application/json ContentType.
type GetMediaUploadURLJSONRequestBody = GetMediaUploadURLJSONBody

// CreateTenantJSONRequestBody defines body for CreateTenant for application/json ContentType.
type CreateTenantJSONRequestBody = CreateTenantRequest

// SetTenantStatusJSONRequestBody defines body for SetTenantStatus for application/json ContentType.
type SetTenantStatusJSONRequestBody = UpdateTenantStatusRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get API documentation
	// (GET /docs/api)
	GetAPIDocs(ctx *echo.Context) error
	// Liveness probe
	// (GET /live)
	Liveness(ctx *echo.Context) error
	// Readiness probe
	// (GET /ready)
	Readiness(ctx *echo.Context) error
	// Get OpenAPI specification .yaml file
	// (GET /spec.yaml)
	GetOpenAPISpec(ctx *echo.Context) error
	// Generate a new API key
	// (POST /v1/apikey/create_key)
	CreateApiKey(ctx *echo.Context) error
	// Get media upload URL
	// (POST /v1/media/upload-url)
	GetMediaUploadURL(ctx *echo.Context) error
	// List all tenants
	// (GET /v1/tenants)
	ListTenants(ctx *echo.Context, params ListTenantsParams) error
	// Create a new tenant
	// (POST /v1/tenants)
	CreateTenant(ctx *echo.Context) error
	// Get tenant by ID
	// (GET /v1/tenants/{id})
	GetTenant(ctx *echo.Context, id openapi_types.UUID) error
	// Update tenant status
	// (PATCH /v1/tenants/{id}/status)
	SetTenantStatus(ctx *echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAPIDocs converts echo context to params.
func (w *ServerInterfaceWrapper) GetAPIDocs(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAPIDocs(ctx)
	return err
}

// Liveness converts echo context to params.
func (w *ServerInterfaceWrapper) Liveness(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Liveness(ctx)
	return err
}

// Readiness converts echo context to params.
func (w *ServerInterfaceWrapper) Readiness(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Readiness(ctx)
	return err
}

// GetOpenAPISpec converts echo context to params.
func (w *ServerInterfaceWrapper) GetOpenAPISpec(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetOpenAPISpec(ctx)
	return err
}

// CreateApiKey converts echo context to params.
func (w *ServerInterfaceWrapper) CreateApiKey(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateApiKey(ctx)
	return err
}

// GetMediaUploadURL converts echo context to params.
func (w *ServerInterfaceWrapper) GetMediaUploadURL(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetMediaUploadURL(ctx)
	return err
}

// ListTenants converts echo context to params.
func (w *ServerInterfaceWrapper) ListTenants(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTenantsParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", ctx.QueryParams(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter offset: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListTenants(ctx, params)
	return err
}

// CreateTenant converts echo context to params.
func (w *ServerInterfaceWrapper) CreateTenant(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateTenant(ctx)
	return err
}

// GetTenant converts echo context to params.
func (w *ServerInterfaceWrapper) GetTenant(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTenant(ctx, id)
	return err
}

// SetTenantStatus converts echo context to params.
func (w *ServerInterfaceWrapper) SetTenantStatus(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SetTenantStatus(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/docs/api", wrapper.GetAPIDocs, options.OperationMiddlewares["getAPIDocs"]...)
	router.GET(options.BaseURL+"/live", wrapper.Liveness, options.OperationMiddlewares["liveness"]...)
	router.GET(options.BaseURL+"/ready", wrapper.Readiness, options.OperationMiddlewares["readiness"]...)
	router.GET(options.BaseURL+"/spec.yaml", wrapper.GetOpenAPISpec, options.OperationMiddlewares["getOpenAPISpec"]...)
	router.POST(options.BaseURL+"/v1/apikey/create_key", wrapper.CreateApiKey, options.OperationMiddlewares["createApiKey"]...)
	router.POST(options.BaseURL+"/v1/media/upload-url", wrapper.GetMediaUploadURL, options.OperationMiddlewares["getMediaUploadURL"]...)
	router.GET(options.BaseURL+"/v1/tenants", wrapper.ListTenants, options.OperationMiddlewares["listTenants"]...)
	router.POST(options.BaseURL+"/v1/tenants", wrapper.CreateTenant, options.OperationMiddlewares["createTenant"]...)
	router.GET(options.BaseURL+"/v1/tenants/:id", wrapper.GetTenant, options.OperationMiddlewares["getTenant"]...)
	router.PATCH(options.BaseURL+"/v1/tenants/:id/status", wrapper.SetTenantStatus, options.OperationMiddlewares["setTenantStatus"]...)

}

type BadRequestJSONResponse Error

type ForbiddenJSONResponse AuthErrorResponse

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse AuthErrorResponse

type GetAPIDocsRequestObject struct {
}

type GetAPIDocsResponseObject interface {
	VisitGetAPIDocsResponse(w http.ResponseWriter) error
}

type GetAPIDocs200TexthtmlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetAPIDocs200TexthtmlResponse) VisitGetAPIDocsResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/html")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type LivenessRequestObject struct {
}

type LivenessResponseObject interface {
	VisitLivenessResponse(w http.ResponseWriter) error
}

type Liveness200JSONResponse HealthResponse

func (response Liveness200JSONResponse) VisitLivenessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReadinessRequestObject struct {
}

type ReadinessResponseObject interface {
	VisitReadinessResponse(w http.ResponseWriter) error
}

type Readiness200JSONResponse HealthResponse

func (response Readiness200JSONResponse) VisitReadinessResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetOpenAPISpecRequestObject struct {
}

type GetOpenAPISpecResponseObject interface {
	VisitGetOpenAPISpecResponse(w http.ResponseWriter) error
}

type GetOpenAPISpec200ApplicationyamlResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetOpenAPISpec200ApplicationyamlResponse) VisitGetOpenAPISpecResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/yaml")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type CreateApiKeyRequestObject struct {
	Body *CreateApiKeyJSONRequestBody
}

type CreateApiKeyResponseObject interface {
	VisitCreateApiKeyResponse(w http.ResponseWriter) error
}

type CreateApiKey201JSONResponse CreateAPIKeyResponse

func (response CreateApiKey201JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKey400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateApiKey400JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateApiKey500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateApiKey500JSONResponse) VisitCreateApiKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetMediaUploadURLRequestObject struct {
	Body *GetMediaUploadURLJSONRequestBody
}

type GetMediaUploadURLResponseObject interface {
	VisitGetMediaUploadURLResponse(w http.ResponseWriter) error
}

type GetMediaUploadURL200JSONResponse UploadURLResponse

func (response GetMediaUploadURL200JSONResponse) VisitGetMediaUploadURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMediaUploadURL401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetMediaUploadURL401JSONResponse) VisitGetMediaUploadURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMediaUploadURL403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetMediaUploadURL403JSONResponse) VisitGetMediaUploadURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetMediaUploadURL500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetMediaUploadURL500JSONResponse) VisitGetMediaUploadURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenantsRequestObject struct {
	Params ListTenantsParams
}

type ListTenantsResponseObject interface {
	VisitListTenantsResponse(w http.ResponseWriter) error
}

type ListTenants200JSONResponse TenantListResponse

func (response ListTenants200JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenants400JSONResponse struct{ BadRequestJSONResponse }

func (response ListTenants400JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListTenants500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListTenants500JSONResponse) VisitListTenantsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenantRequestObject struct {
	Body *CreateTenantJSONRequestBody
}

type CreateTenantResponseObject interface {
	VisitCreateTenantResponse(w http.ResponseWriter) error
}

type CreateTenant201JSONResponse Tenant

func (response CreateTenant201JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTenant400JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTenant500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateTenant500JSONResponse) VisitCreateTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenantRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetTenantResponseObject interface {
	VisitGetTenantResponse(w http.ResponseWriter) error
}

type GetTenant200JSONResponse Tenant

func (response GetTenant200JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant400JSONResponse struct{ BadRequestJSONResponse }

func (response GetTenant400JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTenant404JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTenant500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetTenant500JSONResponse) VisitGetTenantResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SetTenantStatusRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *SetTenantStatusJSONRequestBody
}

type SetTenantStatusResponseObject interface {
	VisitSetTenantStatusResponse(w http.ResponseWriter) error
}

type SetTenantStatus200JSONResponse Tenant

func (response SetTenantStatus200JSONResponse) VisitSetTenantStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SetTenantStatus400JSONResponse struct{ BadRequestJSONResponse }

func (response SetTenantStatus400JSONResponse) VisitSetTenantStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SetTenantStatus404JSONResponse struct{ NotFoundJSONResponse }

func (response SetTenantStatus404JSONResponse) VisitSetTenantStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SetTenantStatus500JSONResponse struct{ InternalErrorJSONResponse }

func (response SetTenantStatus500JSONResponse) VisitSetTenantStatusResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get API documentation
	// (GET /docs/api)
	GetAPIDocs(ctx context.Context, request GetAPIDocsRequestObject) (GetAPIDocsResponseObject, error)
	// Liveness probe
	// (GET /live)
	Liveness(ctx context.Context, request LivenessRequestObject) (LivenessResponseObject, error)
	// Readiness probe
	// (GET /ready)
	Readiness(ctx context.Context, request ReadinessRequestObject) (ReadinessResponseObject, error)
	// Get OpenAPI specification .yaml file
	// (GET /spec.yaml)
	GetOpenAPISpec(ctx context.Context, request GetOpenAPISpecRequestObject) (GetOpenAPISpecResponseObject, error)
	// Generate a new API key
	// (POST /v1/apikey/create_key)
	CreateApiKey(ctx context.Context, request CreateApiKeyRequestObject) (CreateApiKeyResponseObject, error)
	// Get media upload URL
	// (POST /v1/media/upload-url)
	GetMediaUploadURL(ctx context.Context, request GetMediaUploadURLRequestObject) (GetMediaUploadURLResponseObject, error)
	// List all tenants
	// (GET /v1/tenants)
	ListTenants(ctx context.Context, request ListTenantsRequestObject) (ListTenantsResponseObject, error)
	// Create a new tenant
	// (POST /v1/tenants)
	CreateTenant(ctx context.Context, request CreateTenantRequestObject) (CreateTenantResponseObject, error)
	// Get tenant by ID
	// (GET /v1/tenants/{id})
	GetTenant(ctx context.Context, request GetTenantRequestObject) (GetTenantResponseObject, error)
	// Update tenant status
	// (PATCH /v1/tenants/{id}/status)
	SetTenantStatus(ctx context.Context, request SetTenantStatusRequestObject) (SetTenantStatusResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAPIDocs operation middleware
func (sh *strictHandler) GetAPIDocs(ctx *echo.Context) error {
	var request GetAPIDocsRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAPIDocs(ctx.Request().Context(), request.(GetAPIDocsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAPIDocs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetAPIDocsResponseObject); ok {
		return validResponse.VisitGetAPIDocsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Liveness operation middleware
func (sh *strictHandler) Liveness(ctx *echo.Context) error {
	var request LivenessRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Liveness(ctx.Request().Context(), request.(LivenessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Liveness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(LivenessResponseObject); ok {
		return validResponse.VisitLivenessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Readiness operation middleware
func (sh *strictHandler) Readiness(ctx *echo.Context) error {
	var request ReadinessRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Readiness(ctx.Request().Context(), request.(ReadinessRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readiness")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ReadinessResponseObject); ok {
		return validResponse.VisitReadinessResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetOpenAPISpec operation middleware
func (sh *strictHandler) GetOpenAPISpec(ctx *echo.Context) error {
	var request GetOpenAPISpecRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetOpenAPISpec(ctx.Request().Context(), request.(GetOpenAPISpecRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetOpenAPISpec")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetOpenAPISpecResponseObject); ok {
		return validResponse.VisitGetOpenAPISpecResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateApiKey operation middleware
func (sh *strictHandler) CreateApiKey(ctx *echo.Context) error {
	var request CreateApiKeyRequestObject

	var body CreateApiKeyJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateApiKey(ctx.Request().Context(), request.(CreateApiKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateApiKey")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateApiKeyResponseObject); ok {
		return validResponse.VisitCreateApiKeyResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetMediaUploadURL operation middleware
func (sh *strictHandler) GetMediaUploadURL(ctx *echo.Context) error {
	var request GetMediaUploadURLRequestObject

	var body GetMediaUploadURLJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetMediaUploadURL(ctx.Request().Context(), request.(GetMediaUploadURLRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMediaUploadURL")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetMediaUploadURLResponseObject); ok {
		return validResponse.VisitGetMediaUploadURLResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListTenants operation middleware
func (sh *strictHandler) ListTenants(ctx *echo.Context, params ListTenantsParams) error {
	var request ListTenantsRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTenants(ctx.Request().Context(), request.(ListTenantsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTenants")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListTenantsResponseObject); ok {
		return validResponse.VisitListTenantsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateTenant operation middleware
func (sh *strictHandler) CreateTenant(ctx *echo.Context) error {
	var request CreateTenantRequestObject

	var body CreateTenantJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTenant(ctx.Request().Context(), request.(CreateTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTenant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateTenantResponseObject); ok {
		return validResponse.VisitCreateTenantResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetTenant operation middleware
func (sh *strictHandler) GetTenant(ctx *echo.Context, id openapi_types.UUID) error {
	var request GetTenantRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTenant(ctx.Request().Context(), request.(GetTenantRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTenant")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetTenantResponseObject); ok {
		return validResponse.VisitGetTenantResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SetTenantStatus operation middleware
func (sh *strictHandler) SetTenantStatus(ctx *echo.Context, id openapi_types.UUID) error {
	var request SetTenantStatusRequestObject

	request.Id = id

	var body SetTenantStatusJSONRequestBody
	if err := ctx.Bind(&body); err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SetTenantStatus(ctx.Request().Context(), request.(SetTenantStatusRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SetTenantStatus")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SetTenantStatusResponseObject); ok {
		return validResponse.VisitSetTenantStatusResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
