// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countTenants = `-- name: CountTenants :one
SELECT
	COUNT(*)
FROM
	tenants
`

func (q *Queries) CountTenants(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTenants)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTenantsByStatus = `-- name: CountTenantsByStatus :one
SELECT
	COUNT(*)
FROM
	tenants
WHERE
	status = $1
`

func (q *Queries) CountTenantsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countTenantsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO
	tenants (name, email)
VALUES
	($1, $2)
RETURNING
	id, name, email, status, created_at, updated_at
`

type CreateTenantParams struct {
	Name  string
	Email string
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Name, arg.Email)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTenantByEmail = `-- name: GetActiveTenantByEmail :one
SELECT
	id, name, email, status, created_at, updated_at
FROM
	tenants
WHERE
	email = $1
	AND status = 'active'
`

func (q *Queries) GetActiveTenantByEmail(ctx context.Context, email string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getActiveTenantByEmail, email)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT
	id, name, email, status, created_at, updated_at
FROM
	tenants
WHERE
	id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT
	id, name, email, status, created_at, updated_at
FROM
	tenants
ORDER BY
	created_at DESC,
	id DESC
LIMIT
	$1
OFFSET
	$2
`

type ListTenantsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsByEmail = `-- name: ListTenantsByEmail :many
SELECT
	id, name, email, status, created_at, updated_at
FROM
	tenants
WHERE
	email = $1
ORDER BY
	created_at DESC,
	id DESC
`

func (q *Queries) ListTenantsByEmail(ctx context.Context, email string) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantsByStatus = `-- name: ListTenantsByStatus :many
SELECT
	id, name, email, status, created_at, updated_at
FROM
	tenants
WHERE
	status = $1
ORDER BY
	created_at DESC,
	id DESC
LIMIT
	$2
OFFSET
	$3
`

type ListTenantsByStatusParams struct {
	Status string
	Limit  int32
	Offset int32
}

func (q *Queries) ListTenantsByStatus(ctx context.Context, arg ListTenantsByStatusParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Tenant
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTenantStatus = `-- name: SetTenantStatus :one
UPDATE tenants
SET
	status = $1
WHERE
	id = $2
RETURNING
	id, name, email, status, created_at, updated_at
`

type SetTenantStatusParams struct {
	Status string
	ID     pgtype.UUID
}

func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantStatus, arg.Status, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET
	name = $1,
	email = $2
WHERE
	id = $3
RETURNING
	id, name, email, status, created_at, updated_at
`

type UpdateTenantParams struct {
	Name  string
	Email string
	ID    pgtype.UUID
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant, arg.Name, arg.Email, arg.ID)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
